title: "(⚠️執筆中) GitHubでチーム開発を始めよう"
summary: |-
  Git と GitHub を使ったチーム開発のワークフローを紹介します。

  がっつり使ったことは無いけれどなんとなく知っている人に向けて、 GUI ツールのセットアップ、変更のアップロードとプルリクエストの提出、  レビュー指摘の修正からマージまで、基本的なチーム開発の流れを説明します。

  ⚠️私事ですが、現在共同開発プロジェクト立ち上がりに参加しており、  メンバーへの Git レクチャーのため過去の資産を掘り起こしています。

  内容は随時更新していきます。

topics: ["git", "github"]
published: true
price: 0
chapters:
  - summary
  - setup-dev-0-index
  - setup-dev-git
  - setup-dev-ssh
  - setup-dev-github
  - setup-dev-sourcetree
  - developer-0-index
  - developer-clone-repository
  - developer-clean-workspace
  - developer-create-develop-branch
  - developer-upload-changes
  - developer-submit-review
  - developer-fix-review-feedback
  - developer-cleanup
  - developer-get-latest
  - developer-fix-conflict
  - developer-fix-conflict-web
  - reviewer-0-index
  - reviewer-review
  - reviewer-check-fix
  - reviewer-marge-changes


